/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.bootstrap.DemoDataGenerator;
import org.example.domain.Consumer;
import org.example.domain.Facility;
import org.example.domain.FacilityLocationProblem;
import org.example.persistence.FacilityLocationProblemRepository;
import org.example.solver.FacilityLocationConstraintProvider;
import org.optaplanner.core.api.solver.SolverFactory;
import org.optaplanner.core.config.solver.SolverConfig;

import java.time.Duration;
import java.util.Optional;

public class App {

    public static void main(String[] args) {
        SolverFactory<FacilityLocationProblem> solverFactory = SolverFactory.create(new SolverConfig()
                .withSolutionClass(FacilityLocationProblem.class)
                .withEntityClasses(Facility.class, Consumer.class)
                .withConstraintProviderClass(FacilityLocationConstraintProvider.class)
                // The solver runs only for 5 seconds on this small dataset.
                // It's recommended to run for at least 5 minutes ("5m") otherwise.
                .withTerminationSpentLimit(Duration.ofSeconds(10)));

        FacilityLocationProblemRepository repo = new FacilityLocationProblemRepository();
        DemoDataGenerator generator = new DemoDataGenerator(repo);
        generator.generateDemoData();
        Optional<FacilityLocationProblem> maybeSolution = repo.solution();
        maybeSolution.ifPresent(facilityLocationProblem -> {
            System.out.println(maybeSolution.toString());
            long start = System.currentTimeMillis();
            FacilityLocationProblem problem = solverFactory.buildSolver().solve(facilityLocationProblem);
            long finish = System.currentTimeMillis();
            long timeElapsed = finish - start;
            System.out.println(problem.toString());
            System.out.println("Time: " + timeElapsed);
        });
    }
}
