INSERT INTO "COUNTRIES" VALUES (1, 'USA');
INSERT INTO "COUNTRIES" VALUES (2, 'France');
INSERT INTO "COUNTRIES" VALUES (3, 'Brazil');
INSERT INTO "COUNTRIES" VALUES (4, 'Italy');
INSERT INTO "COUNTRIES" VALUES (5, 'Canada');